POST http://localhost:8080/events/1/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imhhc2VlYi5raGFuQGhleXRvcnVzLmNvbSIsImV4cCI6MTcwNzA0NzIxOCwidXNlcklkIjoxfQ.xWv9IyTva-Zs7io7LQC2ZJp68yQUYUxpoN40irb6Caw